---
- name: Add users to Amazom EC2
  hosts: localhost
  become: true
  become_method: sudo 
  user: ec2-user
  
  vars:
    users:
    - bob
    - ben
    - lisa
    - katty
  
  tasks:
  - name: Create user accounts and add users 
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    ansible.builtin.user:  
      name: "{{ item }}"
      state: present
    with_items: "{{ users }}"  

  - name: Create a 2048-bit SSH key for user users in ~users/.ssh/id_rsa
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    ansible.builtin.user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    with_items: "{{ users }}"

  - name: Download csv file to each user home directory 
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/{{ item }}/addresses.cvs
      mode: '0440'
    with_items: "{{ users }}"
