---
- name: Add users to Amazom EC2
  hosts: localhost
  become: true
  become_method: sudo 
  user: ec2-user
  
  vars:
    users:
    - bob
    - ben
    - lisa
    - katty
  
  tasks:
  - name: Create user accounts and add users 
    ansible.builtin.user:  
      name: "{{ item }}"
      state: present
    with_items: "{{ users }}"  

  - name: Create a 2048-bit SSH key for user users in ~users/.ssh/id_rsa
    ansible.builtin.user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    with_items: "{{ users }}"