--- # Connection
# ansible-playbook file.yaml 
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.htmls
- name: Install packages
  hosts: localhost
  become: true
  become_method: sudo 
  user: ec2-user
  tasks: 
  - name: Create file and change file ownership, group and permissions
    ansible.builtin.file:
      path: /tmp/foo.conf
      owner: ec2-user
      group: ec2-user
      mode: '0644'
      state: touch

  - name: Create directory and recursively change ownership of a directory
    ansible.builtin.file:
      path: /tmp/foo
      state: directory
      recurse: yes
      owner: ec2-user
      group: ec2-user