--- # Connection
- name: Install Wordpress
  hosts: all
  become: true
  become_method: sudo 
  user: ec2-user
  tasks:

  - name: Install mariadb
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    package: 
      name: "{{ item }}" 
      state: present
    with_items:
    - mariadb
    notify: 
    - Start DB server

  handlers:
  - name: Start DB server
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    systemd: 
      name: mariadb 
      state: restarted
      enabled: true