---
- name: Add ec2
  hosts: localhost
  
  vars:
    keypair: laptop
    instance_type: t2.micro
    image: ami-074cce78125f09d61
    region: us-east-2
    count: 5
  
  tasks:
  #Basic provision example
  - amazon.aws.ec2:
      key_name: "{{ keypair }}"                       
      instance_type: "{{ instance_type }}"                
      image: "{{ image }}"           
      wait: yes
      count: "{{ count }}"
      region: "{{ region }}"                      
